# Generated by Django 3.0.8 on 2020-07-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(max_length=100)),
                ('road', models.CharField(max_length=100, null=True)),
                ('landmarks', models.CharField(blank=True, default=None, max_length=100)),
                ('phone', models.CharField(max_length=7)),
                ('additional_requests', models.CharField(blank=True, default=None, max_length=500)),
                ('area', models.CharField(choices=[('Male', 'Male'), ('Hulhumale', 'Hulhumale')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered')], max_length=200)),
            ],
        ),
    ]
