# Generated by Django 3.0.8 on 2020-07-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='item_details',
            field=models.TextField(default=None),
        ),
    ]
